spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/product
    username: postgres
    password: 2025
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml

server:
  port: 8080

app:
  jwt-secret: your-super-secret-key-that-is-long-enough
  jwt-expiration-milliseconds: 604800000 